config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'developers' => 'developers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dev_language.rb
class DevLanguage < ApplicationRecord
  belongs_to :developer
  belongs_to :language
end

app/models/dev_pro_language.rb
class DevProLanguage < ApplicationRecord
  belongs_to :developer
  belongs_to :programming_language
end

app/models/developer.rb
class Developer < ApplicationRecord
  validates :email, uniqueness: true
  validates :email, uniqueness: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  has_many :dev_pro_languages
  has_many :programming_languages, through: :dev_pro_languages
  has_many :dev_languages
  has_many :languages, through: :dev_languages

  def self.search_by_programming_languages(pro_lan)
    if pro_lan.nil? || pro_lan == ""
      self.all
    else
      search_key = pro_lan.split(" ")
      where('`programming_languages`.`name` IN (?) ', search_key)
    end
  end

  def self.search_by_languages(lan)
    if lan.nil? || lan == ""
      self.all
    else
      search_key = lan.split(" ")
      where('`languages`.`code` IN (?) ', search_key)
    end
  end
end

app/models/language.rb
class Language < ApplicationRecord
  validates :code, presence: true

  has_many :dev_languages
  has_many :developers, through: :dev_languages
end

app/models/programming_language.rb
class ProgrammingLanguage < ApplicationRecord
  validates :name, presence: true
  
  has_many :dev_pro_languages
  has_many :developers, through: :dev_pro_languages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  def index
    developers_search = Developer.includes(:programming_languages)
                                .includes(:languages)
                                .search_by_programming_languages(params[:programming_languages])
                                .search_by_languages(params[:languages])
                                .pluck(:id).uniq

    @developers = Developer.includes(:programming_languages).includes(:languages).where(id: developers_search)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/views/developers/index.slim
h1 Developer

= form_tag developers_path, method: :get do
  = label_tag(:programming_languages, "programming languages ")
  = text_field_tag :programming_languages, params[:programming_languages]
  = label_tag(:languages, " languages ")
  = text_field_tag :languages, params[:languages]
  = submit_tag "Search", name: nil

br

table.developer-table
  thead
    tr
      th Email
      th Prgramming Language
      th Language
  tbody
    - @developers.each do |dev|
      tr
        td= dev.email
        td
          - dev.programming_languages.each do |pro_lan|
            span
              = pro_lan.name
              - if pro_lan != dev.programming_languages.last
                | , 
        td
          - dev.languages.each do |lan|
            span
              = lan.code
              - if lan != dev.languages.last
                | , 
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>